(cl:defpackage mcr_manipulation_msgs-msg
  (:use )
  (:export
   "<JOINTSPACEWAYPOINTSLIST>"
   "JOINTSPACEWAYPOINTSLIST"
   "<SPHERICALSAMPLERPARAMETERS>"
   "SPHERICALSAMPLERPARAMETERS"
   "<COMPONENTWISECARTESIANDIFFERENCE>"
   "COMPONENTWISECARTESIANDIFFERENCE"
   "<JOINTDISTANCE>"
   "JOINTDISTANCE"
   "<GRIPPERCOMMAND>"
   "GRIPPERCOMMAND"
   "<GRASPLIST>"
   "GRASPLIST"
  ))

