// Generated by gencpp from file mir_navigation_msgs/OrientToBaseResult.msg
// DO NOT EDIT!


#ifndef MIR_NAVIGATION_MSGS_MESSAGE_ORIENTTOBASERESULT_H
#define MIR_NAVIGATION_MSGS_MESSAGE_ORIENTTOBASERESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mir_navigation_msgs
{
template <class ContainerAllocator>
struct OrientToBaseResult_
{
  typedef OrientToBaseResult_<ContainerAllocator> Type;

  OrientToBaseResult_()
    : succeed(false)  {
    }
  OrientToBaseResult_(const ContainerAllocator& _alloc)
    : succeed(false)  {
  (void)_alloc;
    }



   typedef uint8_t _succeed_type;
  _succeed_type succeed;




  typedef boost::shared_ptr< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> const> ConstPtr;

}; // struct OrientToBaseResult_

typedef ::mir_navigation_msgs::OrientToBaseResult_<std::allocator<void> > OrientToBaseResult;

typedef boost::shared_ptr< ::mir_navigation_msgs::OrientToBaseResult > OrientToBaseResultPtr;
typedef boost::shared_ptr< ::mir_navigation_msgs::OrientToBaseResult const> OrientToBaseResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mir_navigation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mir_navigation_msgs': ['/home/hp/c_w/devel/share/mir_navigation_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8d9c3b918a0afafe09791ef8d7853918";
  }

  static const char* value(const ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8d9c3b918a0afafeULL;
  static const uint64_t static_value2 = 0x09791ef8d7853918ULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_navigation_msgs/OrientToBaseResult";
  }

  static const char* value(const ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#result definition\n\
bool succeed\n\
";
  }

  static const char* value(const ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.succeed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrientToBaseResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_navigation_msgs::OrientToBaseResult_<ContainerAllocator>& v)
  {
    s << indent << "succeed: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.succeed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_NAVIGATION_MSGS_MESSAGE_ORIENTTOBASERESULT_H
