// Generated by gencpp from file mir_navigation_msgs/OrientToBaseGoal.msg
// DO NOT EDIT!


#ifndef MIR_NAVIGATION_MSGS_MESSAGE_ORIENTTOBASEGOAL_H
#define MIR_NAVIGATION_MSGS_MESSAGE_ORIENTTOBASEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mir_navigation_msgs
{
template <class ContainerAllocator>
struct OrientToBaseGoal_
{
  typedef OrientToBaseGoal_<ContainerAllocator> Type;

  OrientToBaseGoal_()
    : distance(0.0)  {
    }
  OrientToBaseGoal_(const ContainerAllocator& _alloc)
    : distance(0.0)  {
  (void)_alloc;
    }



   typedef float _distance_type;
  _distance_type distance;




  typedef boost::shared_ptr< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> const> ConstPtr;

}; // struct OrientToBaseGoal_

typedef ::mir_navigation_msgs::OrientToBaseGoal_<std::allocator<void> > OrientToBaseGoal;

typedef boost::shared_ptr< ::mir_navigation_msgs::OrientToBaseGoal > OrientToBaseGoalPtr;
typedef boost::shared_ptr< ::mir_navigation_msgs::OrientToBaseGoal const> OrientToBaseGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mir_navigation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'mir_navigation_msgs': ['/home/hp/c_w/devel/share/mir_navigation_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6e77fb10f0c8b4833ec273aa9ac74459";
  }

  static const char* value(const ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6e77fb10f0c8b483ULL;
  static const uint64_t static_value2 = 0x3ec273aa9ac74459ULL;
};

template<class ContainerAllocator>
struct DataType< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mir_navigation_msgs/OrientToBaseGoal";
  }

  static const char* value(const ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal definition\n\
float32 distance\n\
";
  }

  static const char* value(const ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OrientToBaseGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mir_navigation_msgs::OrientToBaseGoal_<ContainerAllocator>& v)
  {
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MIR_NAVIGATION_MSGS_MESSAGE_ORIENTTOBASEGOAL_H
