// Generated by gencpp from file mcr_manipulation_msgs/ComponentWiseCartesianDifference.msg
// DO NOT EDIT!


#ifndef MCR_MANIPULATION_MSGS_MESSAGE_COMPONENTWISECARTESIANDIFFERENCE_H
#define MCR_MANIPULATION_MSGS_MESSAGE_COMPONENTWISECARTESIANDIFFERENCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Vector3.h>
#include <geometry_msgs/Vector3.h>

namespace mcr_manipulation_msgs
{
template <class ContainerAllocator>
struct ComponentWiseCartesianDifference_
{
  typedef ComponentWiseCartesianDifference_<ContainerAllocator> Type;

  ComponentWiseCartesianDifference_()
    : header()
    , linear()
    , angular()  {
    }
  ComponentWiseCartesianDifference_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , linear(_alloc)
    , angular(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _linear_type;
  _linear_type linear;

   typedef  ::geometry_msgs::Vector3_<ContainerAllocator>  _angular_type;
  _angular_type angular;




  typedef boost::shared_ptr< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> const> ConstPtr;

}; // struct ComponentWiseCartesianDifference_

typedef ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<std::allocator<void> > ComponentWiseCartesianDifference;

typedef boost::shared_ptr< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference > ComponentWiseCartesianDifferencePtr;
typedef boost::shared_ptr< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference const> ComponentWiseCartesianDifferenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mcr_manipulation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'mcr_common_msgs': ['/home/hp/c_w/src/ciit_robotics_lab/mcr_common_msgs/msg'], 'shape_msgs': ['/opt/ros/indigo/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/indigo/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/indigo/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/indigo/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'mcr_manipulation_msgs': ['/home/hp/c_w/src/ciit_robotics_lab/mcr_manipulation_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "09119d3b0067bd05b1a6696c168cebb3";
  }

  static const char* value(const ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x09119d3b0067bd05ULL;
  static const uint64_t static_value2 = 0xb1a6696c168cebb3ULL;
};

template<class ContainerAllocator>
struct DataType< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcr_manipulation_msgs/ComponentWiseCartesianDifference";
  }

  static const char* value(const ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message expresses the difference between two poses broken\n\
# into its linear and angular parts, w.r.t. the reference\n\
# coordinate frame and time as provided in the header.\n\
\n\
std_msgs/Header header\n\
geometry_msgs/Vector3 linear\n\
geometry_msgs/Vector3 angular\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.linear);
      stream.next(m.angular);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ComponentWiseCartesianDifference_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcr_manipulation_msgs::ComponentWiseCartesianDifference_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "linear: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.linear);
    s << indent << "angular: ";
    s << std::endl;
    Printer< ::geometry_msgs::Vector3_<ContainerAllocator> >::stream(s, indent + "  ", v.angular);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCR_MANIPULATION_MSGS_MESSAGE_COMPONENTWISECARTESIANDIFFERENCE_H
