(cl:defpackage mir_navigation_msgs-msg
  (:use )
  (:export
   "<ORIENTTOBASEACTION>"
   "ORIENTTOBASEACTION"
   "<ORIENTTOBASERESULT>"
   "ORIENTTOBASERESULT"
   "<ORIENTTOBASEACTIONFEEDBACK>"
   "ORIENTTOBASEACTIONFEEDBACK"
   "<ORIENTTOBASEGOAL>"
   "ORIENTTOBASEGOAL"
   "<ORIENTTOBASEACTIONRESULT>"
   "ORIENTTOBASEACTIONRESULT"
   "<ORIENTTOBASEACTIONGOAL>"
   "ORIENTTOBASEACTIONGOAL"
   "<ORIENTTOBASEFEEDBACK>"
   "ORIENTTOBASEFEEDBACK"
  ))

