; Auto-generated. Do not edit!


(cl:in-package mir_navigation_msgs-msg)


;//! \htmlinclude OrientToBaseResult.msg.html

(cl:defclass <OrientToBaseResult> (roslisp-msg-protocol:ros-message)
  ((succeed
    :reader succeed
    :initarg :succeed
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass OrientToBaseResult (<OrientToBaseResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <OrientToBaseResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'OrientToBaseResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mir_navigation_msgs-msg:<OrientToBaseResult> is deprecated: use mir_navigation_msgs-msg:OrientToBaseResult instead.")))

(cl:ensure-generic-function 'succeed-val :lambda-list '(m))
(cl:defmethod succeed-val ((m <OrientToBaseResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mir_navigation_msgs-msg:succeed-val is deprecated.  Use mir_navigation_msgs-msg:succeed instead.")
  (succeed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <OrientToBaseResult>) ostream)
  "Serializes a message object of type '<OrientToBaseResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'succeed) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <OrientToBaseResult>) istream)
  "Deserializes a message object of type '<OrientToBaseResult>"
    (cl:setf (cl:slot-value msg 'succeed) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<OrientToBaseResult>)))
  "Returns string type for a message object of type '<OrientToBaseResult>"
  "mir_navigation_msgs/OrientToBaseResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'OrientToBaseResult)))
  "Returns string type for a message object of type 'OrientToBaseResult"
  "mir_navigation_msgs/OrientToBaseResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<OrientToBaseResult>)))
  "Returns md5sum for a message object of type '<OrientToBaseResult>"
  "8d9c3b918a0afafe09791ef8d7853918")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'OrientToBaseResult)))
  "Returns md5sum for a message object of type 'OrientToBaseResult"
  "8d9c3b918a0afafe09791ef8d7853918")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<OrientToBaseResult>)))
  "Returns full string definition for message of type '<OrientToBaseResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool succeed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'OrientToBaseResult)))
  "Returns full string definition for message of type 'OrientToBaseResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#result definition~%bool succeed~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <OrientToBaseResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <OrientToBaseResult>))
  "Converts a ROS message object to a list"
  (cl:list 'OrientToBaseResult
    (cl:cons ':succeed (succeed msg))
))
