; Auto-generated. Do not edit!


(cl:in-package mir_navigation_msgs-msg)


;//! \htmlinclude OrientToBaseFeedback.msg.html

(cl:defclass <OrientToBaseFeedback> (roslisp-msg-protocol:ros-message)
  ((result
    :reader result
    :initarg :result
    :type cl:integer
    :initform 0))
)

(cl:defclass OrientToBaseFeedback (<OrientToBaseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <OrientToBaseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'OrientToBaseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name mir_navigation_msgs-msg:<OrientToBaseFeedback> is deprecated: use mir_navigation_msgs-msg:OrientToBaseFeedback instead.")))

(cl:ensure-generic-function 'result-val :lambda-list '(m))
(cl:defmethod result-val ((m <OrientToBaseFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader mir_navigation_msgs-msg:result-val is deprecated.  Use mir_navigation_msgs-msg:result instead.")
  (result m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <OrientToBaseFeedback>) ostream)
  "Serializes a message object of type '<OrientToBaseFeedback>"
  (cl:let* ((signed (cl:slot-value msg 'result)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 4294967296) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <OrientToBaseFeedback>) istream)
  "Deserializes a message object of type '<OrientToBaseFeedback>"
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'result) (cl:if (cl:< unsigned 2147483648) unsigned (cl:- unsigned 4294967296))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<OrientToBaseFeedback>)))
  "Returns string type for a message object of type '<OrientToBaseFeedback>"
  "mir_navigation_msgs/OrientToBaseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'OrientToBaseFeedback)))
  "Returns string type for a message object of type 'OrientToBaseFeedback"
  "mir_navigation_msgs/OrientToBaseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<OrientToBaseFeedback>)))
  "Returns md5sum for a message object of type '<OrientToBaseFeedback>"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'OrientToBaseFeedback)))
  "Returns md5sum for a message object of type 'OrientToBaseFeedback"
  "034a8e20d6a306665e3a5b340fab3f09")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<OrientToBaseFeedback>)))
  "Returns full string definition for message of type '<OrientToBaseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'OrientToBaseFeedback)))
  "Returns full string definition for message of type 'OrientToBaseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%int32 result~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <OrientToBaseFeedback>))
  (cl:+ 0
     4
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <OrientToBaseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'OrientToBaseFeedback
    (cl:cons ':result (result msg))
))
