// Generated by gencpp from file mcr_manipulation_msgs/GripperCommand.msg
// DO NOT EDIT!


#ifndef MCR_MANIPULATION_MSGS_MESSAGE_GRIPPERCOMMAND_H
#define MCR_MANIPULATION_MSGS_MESSAGE_GRIPPERCOMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mcr_manipulation_msgs
{
template <class ContainerAllocator>
struct GripperCommand_
{
  typedef GripperCommand_<ContainerAllocator> Type;

  GripperCommand_()
    : command(0)  {
    }
  GripperCommand_(const ContainerAllocator& _alloc)
    : command(0)  {
  (void)_alloc;
    }



   typedef int32_t _command_type;
  _command_type command;


    enum { OPEN = 0 };
     enum { CLOSE = 1 };
 

  typedef boost::shared_ptr< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> const> ConstPtr;

}; // struct GripperCommand_

typedef ::mcr_manipulation_msgs::GripperCommand_<std::allocator<void> > GripperCommand;

typedef boost::shared_ptr< ::mcr_manipulation_msgs::GripperCommand > GripperCommandPtr;
typedef boost::shared_ptr< ::mcr_manipulation_msgs::GripperCommand const> GripperCommandConstPtr;

// constants requiring out of line definition

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace mcr_manipulation_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'mcr_common_msgs': ['/home/hp/c_w/src/ciit_robotics_lab/mcr_common_msgs/msg'], 'shape_msgs': ['/opt/ros/indigo/share/shape_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'moveit_msgs': ['/opt/ros/indigo/share/moveit_msgs/cmake/../msg'], 'trajectory_msgs': ['/opt/ros/indigo/share/trajectory_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'object_recognition_msgs': ['/opt/ros/indigo/share/object_recognition_msgs/cmake/../msg'], 'octomap_msgs': ['/opt/ros/indigo/share/octomap_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'mcr_manipulation_msgs': ['/home/hp/c_w/src/ciit_robotics_lab/mcr_manipulation_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "66cc2e459a9e7908ce52dd06f60fe935";
  }

  static const char* value(const ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x66cc2e459a9e7908ULL;
  static const uint64_t static_value2 = 0xce52dd06f60fe935ULL;
};

template<class ContainerAllocator>
struct DataType< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mcr_manipulation_msgs/GripperCommand";
  }

  static const char* value(const ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 command\n\
\n\
int32 OPEN = 0\n\
int32 CLOSE = 1\n\
";
  }

  static const char* value(const ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GripperCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::mcr_manipulation_msgs::GripperCommand_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<int32_t>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MCR_MANIPULATION_MSGS_MESSAGE_GRIPPERCOMMAND_H
